title: Darcnia Campaign
description: D&D 2024 reference hub for the floating continent of Darcnia
baseurl: "/Darcnia"
url: "https://cosmicphoenix171.github.io"
permalink: pretty
markdown: kramdown
collections: {}
include:
  - darcnia-campaign
  - app/js/app-config.js
  - app/js/character-db.js
  - app/js/firebase-config.js
  - app/js/pricing.js
exclude:
  - node_modules
  - package-lock.json
  - README.md
  - LICENSE
  - .vscode
  - Gemfile.lock
  - scripts
plugins: []
defaults:
  - scope:
      path: ""
    values:
      layout: default
